2023-04-03 16:29:17,376:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-03 16:29:29,396:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-03 16:29:29,574:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-04-03 16:29:56,104:WARNING:STDOUT:CMS:2023-04-03 16:29:56,104 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-04-03 16:29:56,105:WARNING:STDOUT:CMS:2023-04-03 16:29:56,105 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-03 16:29:56,470:WARNING:STDOUT:CMS:2023-04-03 16:29:56,470 INFO sqlalchemy.engine.Engine select current_schema()
2023-04-03 16:29:56,471:WARNING:STDOUT:CMS:2023-04-03 16:29:56,470 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-03 16:29:56,681:WARNING:STDOUT:CMS:2023-04-03 16:29:56,680 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-04-03 16:29:56,681:WARNING:STDOUT:CMS:2023-04-03 16:29:56,681 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-03 16:29:57,084:WARNING:STDOUT:CMS:2023-04-03 16:29:57,084 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-03 16:29:57,086:WARNING:STDOUT:CMS:2023-04-03 16:29:57,086 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-04-03 16:29:57,086:WARNING:STDOUT:CMS:2023-04-03 16:29:57,086 INFO sqlalchemy.engine.Engine [generated in 0.00024s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-04-03 16:29:57,343:WARNING:STDOUT:CMS:2023-04-03 16:29:57,343 INFO sqlalchemy.engine.Engine COMMIT
2023-04-03 16:29:57,382:WARNING:STDOUT:CMS:2023-04-03 16:29:57,382 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-03 16:29:57,383:WARNING:STDOUT:CMS:2023-04-03 16:29:57,383 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-04-03 16:29:57,383:WARNING:STDOUT:CMS:2023-04-03 16:29:57,383 INFO sqlalchemy.engine.Engine [generated in 0.00015s] {'name': 'Cust Cart', 'hiden': True}
2023-04-03 16:29:57,703:WARNING:STDOUT:CMS:2023-04-03 16:29:57,703 INFO sqlalchemy.engine.Engine COMMIT
2023-04-03 16:29:57,911:WARNING:STDOUT:CMS:2023-04-03 16:29:57,911 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-03 16:29:57,915:WARNING:STDOUT:CMS:2023-04-03 16:29:57,915 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-04-03 16:29:57,915:WARNING:STDOUT:CMS:FROM user_grup
2023-04-03 16:29:57,915:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-04-03 16:29:57,915:WARNING:STDOUT:CMS:2023-04-03 16:29:57,915 INFO sqlalchemy.engine.Engine [generated in 0.00031s] {'pk_1': 1}
2023-04-03 16:29:57,962:WARNING:STDOUT:CMS:2023-04-03 16:29:57,961 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-04-03 16:29:57,962:WARNING:STDOUT:CMS:2023-04-03 16:29:57,962 INFO sqlalchemy.engine.Engine [generated in 0.00046s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-04-03 16:29:58,107:WARNING:STDOUT:CMS:2023-04-03 16:29:58,107 INFO sqlalchemy.engine.Engine COMMIT
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-03 16:29:58,314:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-03 16:29:58,315:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 16:32:38,826:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 16:32:50,841:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 16:32:51,028:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-04-29 16:33:05,152:WARNING:STDOUT:CMS:2023-04-29 16:33:05,152 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-04-29 16:33:05,153:WARNING:STDOUT:CMS:2023-04-29 16:33:05,153 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 16:33:05,578:WARNING:STDOUT:CMS:2023-04-29 16:33:05,578 INFO sqlalchemy.engine.Engine select current_schema()
2023-04-29 16:33:05,578:WARNING:STDOUT:CMS:2023-04-29 16:33:05,578 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 16:33:05,972:WARNING:STDOUT:CMS:2023-04-29 16:33:05,972 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-04-29 16:33:05,973:WARNING:STDOUT:CMS:2023-04-29 16:33:05,973 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 16:33:06,384:WARNING:STDOUT:CMS:2023-04-29 16:33:06,384 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 16:33:06,388:WARNING:STDOUT:CMS:2023-04-29 16:33:06,388 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-04-29 16:33:06,388:WARNING:STDOUT:CMS:2023-04-29 16:33:06,388 INFO sqlalchemy.engine.Engine [generated in 0.00052s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-04-29 16:33:06,487:WARNING:STDOUT:CMS:2023-04-29 16:33:06,487 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 16:33:06,587:WARNING:STDOUT:CMS:2023-04-29 16:33:06,587 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 16:33:06,589:WARNING:STDOUT:CMS:2023-04-29 16:33:06,589 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-04-29 16:33:06,589:WARNING:STDOUT:CMS:2023-04-29 16:33:06,589 INFO sqlalchemy.engine.Engine [generated in 0.00047s] {'name': 'Cust Cart', 'hiden': True}
2023-04-29 16:33:06,997:WARNING:STDOUT:CMS:2023-04-29 16:33:06,997 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 16:33:07,200:WARNING:STDOUT:CMS:2023-04-29 16:33:07,200 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 16:33:07,205:WARNING:STDOUT:CMS:2023-04-29 16:33:07,205 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-04-29 16:33:07,205:WARNING:STDOUT:CMS:FROM user_grup
2023-04-29 16:33:07,205:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-04-29 16:33:07,206:WARNING:STDOUT:CMS:2023-04-29 16:33:07,206 INFO sqlalchemy.engine.Engine [generated in 0.00076s] {'pk_1': 1}
2023-04-29 16:33:07,620:WARNING:STDOUT:CMS:2023-04-29 16:33:07,620 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-04-29 16:33:07,620:WARNING:STDOUT:CMS:2023-04-29 16:33:07,620 INFO sqlalchemy.engine.Engine [generated in 0.00030s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-04-29 16:33:07,818:WARNING:STDOUT:CMS:2023-04-29 16:33:07,818 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 16:33:08,019:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 16:33:08,019:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 16:33:08,019:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 16:33:08,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 18:38:51,158:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 18:39:03,175:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 18:39:03,362:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-04-29 18:39:28,213:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 18:39:40,229:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-04-29 18:39:40,461:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-04-29 18:39:48,312:WARNING:STDOUT:CMS:2023-04-29 18:39:48,312 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-04-29 18:39:48,313:WARNING:STDOUT:CMS:2023-04-29 18:39:48,313 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 18:39:48,327:WARNING:STDOUT:CMS:2023-04-29 18:39:48,327 INFO sqlalchemy.engine.Engine select current_schema()
2023-04-29 18:39:48,327:WARNING:STDOUT:CMS:2023-04-29 18:39:48,327 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 18:39:48,341:WARNING:STDOUT:CMS:2023-04-29 18:39:48,341 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-04-29 18:39:48,341:WARNING:STDOUT:CMS:2023-04-29 18:39:48,341 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-29 18:39:48,356:WARNING:STDOUT:CMS:2023-04-29 18:39:48,355 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 18:39:48,359:WARNING:STDOUT:CMS:2023-04-29 18:39:48,359 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-04-29 18:39:48,360:WARNING:STDOUT:CMS:2023-04-29 18:39:48,360 INFO sqlalchemy.engine.Engine [generated in 0.00084s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-04-29 18:39:48,518:WARNING:STDOUT:CMS:2023-04-29 18:39:48,518 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 18:39:48,530:WARNING:STDOUT:CMS:2023-04-29 18:39:48,530 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 18:39:48,531:WARNING:STDOUT:CMS:2023-04-29 18:39:48,531 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-04-29 18:39:48,532:WARNING:STDOUT:CMS:2023-04-29 18:39:48,532 INFO sqlalchemy.engine.Engine [generated in 0.00039s] {'name': 'Cust Cart', 'hiden': True}
2023-04-29 18:39:48,734:WARNING:STDOUT:CMS:2023-04-29 18:39:48,734 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 18:39:48,927:WARNING:STDOUT:CMS:2023-04-29 18:39:48,927 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-29 18:39:48,932:WARNING:STDOUT:CMS:2023-04-29 18:39:48,932 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-04-29 18:39:48,932:WARNING:STDOUT:CMS:FROM user_grup
2023-04-29 18:39:48,932:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-04-29 18:39:48,933:WARNING:STDOUT:CMS:2023-04-29 18:39:48,933 INFO sqlalchemy.engine.Engine [generated in 0.00106s] {'pk_1': 1}
2023-04-29 18:39:48,952:WARNING:STDOUT:CMS:2023-04-29 18:39:48,952 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-04-29 18:39:48,952:WARNING:STDOUT:CMS:2023-04-29 18:39:48,952 INFO sqlalchemy.engine.Engine [generated in 0.00033s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-04-29 18:39:49,132:WARNING:STDOUT:CMS:2023-04-29 18:39:49,131 INFO sqlalchemy.engine.Engine COMMIT
2023-04-29 18:39:49,145:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 18:39:49,145:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 18:39:49,145:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-04-29 18:39:49,146:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-05-10 18:39:27,253:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-05-10 18:39:39,275:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-05-10 18:39:39,456:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-05-10 18:39:49,002:WARNING:STDOUT:CMS:2023-05-10 18:39:49,002 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-05-10 18:39:49,003:WARNING:STDOUT:CMS:2023-05-10 18:39:49,003 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-05-10 18:39:49,014:WARNING:STDOUT:CMS:2023-05-10 18:39:49,014 INFO sqlalchemy.engine.Engine select current_schema()
2023-05-10 18:39:49,015:WARNING:STDOUT:CMS:2023-05-10 18:39:49,014 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-05-10 18:39:49,024:WARNING:STDOUT:CMS:2023-05-10 18:39:49,024 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-05-10 18:39:49,025:WARNING:STDOUT:CMS:2023-05-10 18:39:49,025 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-05-10 18:39:49,032:WARNING:STDOUT:CMS:2023-05-10 18:39:49,032 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-10 18:39:49,036:WARNING:STDOUT:CMS:2023-05-10 18:39:49,036 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-05-10 18:39:49,036:WARNING:STDOUT:CMS:2023-05-10 18:39:49,036 INFO sqlalchemy.engine.Engine [generated in 0.00053s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-05-10 18:39:49,057:WARNING:STDOUT:CMS:2023-05-10 18:39:49,057 INFO sqlalchemy.engine.Engine COMMIT
2023-05-10 18:39:49,065:WARNING:STDOUT:CMS:2023-05-10 18:39:49,064 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-10 18:39:49,066:WARNING:STDOUT:CMS:2023-05-10 18:39:49,066 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-05-10 18:39:49,066:WARNING:STDOUT:CMS:2023-05-10 18:39:49,066 INFO sqlalchemy.engine.Engine [generated in 0.00044s] {'name': 'Cust Cart', 'hiden': True}
2023-05-10 18:39:49,204:WARNING:STDOUT:CMS:2023-05-10 18:39:49,204 INFO sqlalchemy.engine.Engine COMMIT
2023-05-10 18:39:49,213:WARNING:STDOUT:CMS:2023-05-10 18:39:49,213 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-10 18:39:49,217:WARNING:STDOUT:CMS:2023-05-10 18:39:49,217 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-05-10 18:39:49,217:WARNING:STDOUT:CMS:FROM user_grup
2023-05-10 18:39:49,217:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-05-10 18:39:49,217:WARNING:STDOUT:CMS:2023-05-10 18:39:49,217 INFO sqlalchemy.engine.Engine [generated in 0.00032s] {'pk_1': 1}
2023-05-10 18:39:49,419:WARNING:STDOUT:CMS:2023-05-10 18:39:49,418 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-05-10 18:39:49,419:WARNING:STDOUT:CMS:2023-05-10 18:39:49,419 INFO sqlalchemy.engine.Engine [generated in 0.00052s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-05-10 18:39:49,613:WARNING:STDOUT:CMS:2023-05-10 18:39:49,613 INFO sqlalchemy.engine.Engine COMMIT
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-05-10 18:39:49,623:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-05-10 18:39:49,624:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-05-10 18:39:49,624:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-05-10 18:39:49,624:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-05-10 18:39:49,624:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-05-10 18:39:49,624:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 18:45:25,876:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 18:45:37,891:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 18:45:38,019:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-22 18:45:44,062:WARNING:STDOUT:CMS:2023-06-22 18:45:44,062 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-22 18:45:44,062:WARNING:STDOUT:CMS:2023-06-22 18:45:44,062 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 18:45:44,309:WARNING:STDOUT:CMS:2023-06-22 18:45:44,309 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-22 18:45:44,309:WARNING:STDOUT:CMS:2023-06-22 18:45:44,309 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 18:45:44,323:WARNING:STDOUT:CMS:2023-06-22 18:45:44,323 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-22 18:45:44,323:WARNING:STDOUT:CMS:2023-06-22 18:45:44,323 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 18:45:44,338:WARNING:STDOUT:CMS:2023-06-22 18:45:44,338 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 18:45:44,341:WARNING:STDOUT:CMS:2023-06-22 18:45:44,341 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-22 18:45:44,341:WARNING:STDOUT:CMS:2023-06-22 18:45:44,341 INFO sqlalchemy.engine.Engine [generated in 0.00042s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-22 18:45:44,689:WARNING:STDOUT:CMS:2023-06-22 18:45:44,689 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 18:45:44,854:WARNING:STDOUT:CMS:2023-06-22 18:45:44,854 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 18:45:44,855:WARNING:STDOUT:CMS:2023-06-22 18:45:44,855 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-06-22 18:45:44,855:WARNING:STDOUT:CMS:2023-06-22 18:45:44,855 INFO sqlalchemy.engine.Engine [generated in 0.00038s] {'name': 'Cust Cart', 'hiden': True}
2023-06-22 18:45:44,870:WARNING:STDOUT:CMS:2023-06-22 18:45:44,870 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 18:45:44,878:WARNING:STDOUT:CMS:2023-06-22 18:45:44,878 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 18:45:44,882:WARNING:STDOUT:CMS:2023-06-22 18:45:44,882 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-06-22 18:45:44,882:WARNING:STDOUT:CMS:FROM user_grup
2023-06-22 18:45:44,882:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-06-22 18:45:44,883:WARNING:STDOUT:CMS:2023-06-22 18:45:44,883 INFO sqlalchemy.engine.Engine [generated in 0.00065s] {'pk_1': 1}
2023-06-22 18:45:44,905:WARNING:STDOUT:CMS:2023-06-22 18:45:44,905 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-06-22 18:45:44,906:WARNING:STDOUT:CMS:2023-06-22 18:45:44,906 INFO sqlalchemy.engine.Engine [generated in 0.00043s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-06-22 18:45:45,018:WARNING:STDOUT:CMS:2023-06-22 18:45:45,018 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 18:45:45,026:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 18:45:45,026:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 18:45:45,026:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 18:45:45,027:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:15:31,249:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:15:43,263:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:15:43,436:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-22 20:16:20,000:WARNING:STDOUT:CMS:2023-06-22 20:16:20,000 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-22 20:16:20,000:WARNING:STDOUT:CMS:2023-06-22 20:16:20,000 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:16:20,002:WARNING:STDOUT:CMS:2023-06-22 20:16:20,002 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-22 20:16:20,002:WARNING:STDOUT:CMS:2023-06-22 20:16:20,002 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:16:20,004:WARNING:STDOUT:CMS:2023-06-22 20:16:20,003 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-22 20:16:20,004:WARNING:STDOUT:CMS:2023-06-22 20:16:20,004 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:16:20,005:WARNING:STDOUT:CMS:2023-06-22 20:16:20,005 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 20:16:20,008:WARNING:STDOUT:CMS:2023-06-22 20:16:20,008 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-22 20:16:20,008:WARNING:STDOUT:CMS:2023-06-22 20:16:20,008 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-22 20:16:20,012:WARNING:STDOUT:CMS:2023-06-22 20:16:20,012 INFO sqlalchemy.engine.Engine ROLLBACK
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:self.dialect.do_execute(
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:cursor.execute(statement, parameters)
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:psycopg2.errors
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:.
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:UniqueViolation
2023-06-22 20:16:20,013:WARNING:STDERR:CMS::
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:duplicate key value violates unique constraint "user_grup_name_key"
2023-06-22 20:16:20,013:WARNING:STDERR:CMS:DETAIL:  Key (name)=(OWNER) already exists.
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:The above exception was the direct cause of the following exception:
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 201, in <module>
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:db_init_new()
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 173, in db_init_new
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:DB.commit()
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 985, in commit
2023-06-22 20:16:20,014:WARNING:STDERR:CMS:raise e
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 981, in commit
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:self.session.commit()
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1903, in commit
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:trans.commit(_to_root=True)
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "<string>", line 2, in commit
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1218, in commit
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:self._prepare_impl()
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "<string>", line 2, in _prepare_impl
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-22 20:16:20,015:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-22 20:16:20,016:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
2023-06-22 20:16:20,016:WARNING:STDERR:CMS:self.session.flush()
2023-06-22 20:16:20,016:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4155, in flush
2023-06-22 20:16:20,016:WARNING:STDERR:CMS:self._flush(objects)
2023-06-22 20:16:20,016:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4292, in _flush
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:transaction.rollback(_capture_exception=True)
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4252, in _flush
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:flush_context.execute()
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:rec.execute(self)
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:util.preloaded.orm_persistence.save_obj(
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:_emit_insert_statements(
2023-06-22 20:16:20,017:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1184, in _emit_insert_statements
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:result = connection.execute(
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:return meth(
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:return connection._execute_clauseelement(
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:ret = self._execute_context(
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:return self._exec_single_context(
2023-06-22 20:16:20,018:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:self._handle_dbapi_exception(
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:self.dialect.do_execute(
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:cursor.execute(statement, parameters)
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:sqlalchemy.exc
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:.
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:IntegrityError
2023-06-22 20:16:20,019:WARNING:STDERR:CMS::
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "user_grup_name_key"
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:DETAIL:  Key (name)=(OWNER) already exists.
2023-06-22 20:16:20,019:WARNING:STDERR:CMS:
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[SQL: INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject]
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[parameters: {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}]
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:16:20,020:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:17:36,876:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-06-22 20:17:36,876:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 12, in <module>
2023-06-22 20:17:36,877:WARNING:STDERR:CMS:import msg
2023-06-22 20:17:36,877:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/msg.py", line 18, in <module>
2023-06-22 20:17:36,882:WARNING:STDERR:CMS:import libs
2023-06-22 20:17:36,883:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/__init__.py", line 127, in <module>
2023-06-22 20:17:36,883:WARNING:STDERR:CMS:alife = udp.send('server_alive', ip=conf.SERVER)
2023-06-22 20:17:36,883:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/udp.py", line 43, in send
2023-06-22 20:17:36,883:WARNING:STDERR:CMS:response = my_client.send(evt, **kwargs)
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 145, in send
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:response = self.getfrom()
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:data = self.s.recv(self.udp_buffer)
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:KeyboardInterrupt
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:17:36,884:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:17:59,947:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:18:11,961:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:18:12,136:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-22 20:18:19,066:WARNING:STDOUT:CMS:2023-06-22 20:18:19,066 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-22 20:18:19,066:WARNING:STDOUT:CMS:2023-06-22 20:18:19,066 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:18:19,081:WARNING:STDOUT:CMS:2023-06-22 20:18:19,081 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-22 20:18:19,081:WARNING:STDOUT:CMS:2023-06-22 20:18:19,081 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:18:19,274:WARNING:STDOUT:CMS:2023-06-22 20:18:19,274 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-22 20:18:19,274:WARNING:STDOUT:CMS:2023-06-22 20:18:19,274 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:18:19,373:WARNING:STDOUT:CMS:2023-06-22 20:18:19,373 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 20:18:19,375:WARNING:STDOUT:CMS:2023-06-22 20:18:19,375 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-06-22 20:18:19,375:WARNING:STDOUT:CMS:2023-06-22 20:18:19,375 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-06-22 20:18:19,390:WARNING:STDOUT:CMS:2023-06-22 20:18:19,390 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 20:18:19,403:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:18:19,403:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:18:19,404:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:19:28,441:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:19:40,455:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:19:40,630:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-22 20:20:09,867:WARNING:STDOUT:CMS:2023-06-22 20:20:09,867 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-22 20:20:09,868:WARNING:STDOUT:CMS:2023-06-22 20:20:09,868 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:20:09,882:WARNING:STDOUT:CMS:2023-06-22 20:20:09,882 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-22 20:20:09,883:WARNING:STDOUT:CMS:2023-06-22 20:20:09,883 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:20:09,893:WARNING:STDOUT:CMS:2023-06-22 20:20:09,893 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-22 20:20:09,893:WARNING:STDOUT:CMS:2023-06-22 20:20:09,893 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:20:10,068:WARNING:STDOUT:CMS:2023-06-22 20:20:10,068 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 20:20:10,072:WARNING:STDOUT:CMS:2023-06-22 20:20:10,072 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-22 20:20:10,072:WARNING:STDOUT:CMS:2023-06-22 20:20:10,072 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-22 20:20:10,274:WARNING:STDOUT:CMS:2023-06-22 20:20:10,274 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:20:10,478:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:20:10,479:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:20:10,479:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:43:59,912:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:44:11,926:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-22 20:44:12,099:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-22 20:44:18,633:WARNING:STDOUT:CMS:2023-06-22 20:44:18,633 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-22 20:44:18,634:WARNING:STDOUT:CMS:2023-06-22 20:44:18,634 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:44:18,834:WARNING:STDOUT:CMS:2023-06-22 20:44:18,834 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-22 20:44:18,834:WARNING:STDOUT:CMS:2023-06-22 20:44:18,834 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:44:18,847:WARNING:STDOUT:CMS:2023-06-22 20:44:18,847 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-22 20:44:18,847:WARNING:STDOUT:CMS:2023-06-22 20:44:18,847 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-22 20:44:19,042:WARNING:STDOUT:CMS:2023-06-22 20:44:19,042 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 20:44:19,046:WARNING:STDOUT:CMS:2023-06-22 20:44:19,046 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-22 20:44:19,046:WARNING:STDOUT:CMS:2023-06-22 20:44:19,046 INFO sqlalchemy.engine.Engine [generated in 0.00052s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-22 20:44:19,244:WARNING:STDOUT:CMS:2023-06-22 20:44:19,244 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 20:44:19,255:WARNING:STDOUT:CMS:2023-06-22 20:44:19,255 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-22 20:44:19,259:WARNING:STDOUT:CMS:2023-06-22 20:44:19,259 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-06-22 20:44:19,259:WARNING:STDOUT:CMS:FROM user_grup
2023-06-22 20:44:19,259:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-06-22 20:44:19,260:WARNING:STDOUT:CMS:2023-06-22 20:44:19,260 INFO sqlalchemy.engine.Engine [generated in 0.00085s] {'pk_1': 1}
2023-06-22 20:44:19,278:WARNING:STDOUT:CMS:2023-06-22 20:44:19,278 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-06-22 20:44:19,278:WARNING:STDOUT:CMS:2023-06-22 20:44:19,278 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-06-22 20:44:19,449:WARNING:STDOUT:CMS:2023-06-22 20:44:19,449 INFO sqlalchemy.engine.Engine COMMIT
2023-06-22 20:44:19,461:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:44:19,462:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-22 20:44:19,463:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:44:19,463:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:44:19,463:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-22 20:44:19,463:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:32:12,761:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-23 07:32:24,777:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-23 07:32:24,942:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-23 07:32:35,630:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-06-23 07:32:35,630:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2023-06-23 07:32:35,636:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2023-06-23 07:32:35,636:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
2023-06-23 07:32:35,636:WARNING:STDERR:CMS:return self.pool.connect()
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 455, in connect
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 719, in checkout
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:rec = pool._do_get()
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2023-06-23 07:32:35,637:WARNING:STDERR:CMS:self._dec_overflow()
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:return self._create_connection()
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 681, in __init__
2023-06-23 07:32:35,638:WARNING:STDERR:CMS:self.__connect()
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 906, in __connect
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 636, in connect
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2023-06-23 07:32:35,639:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:psycopg2
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:.
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:OperationalError
2023-06-23 07:32:35,640:WARNING:STDERR:CMS::
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:connection to server at "192.168.1.6", port 5432 failed: No route to host
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:	Is the server running on that host and accepting TCP/IP connections?
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:
2023-06-23 07:32:35,640:WARNING:STDERR:CMS:The above exception was the direct cause of the following exception:
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 201, in <module>
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:db_init_new()
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 173, in db_init_new
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:DB.commit()
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 985, in commit
2023-06-23 07:32:35,641:WARNING:STDERR:CMS:raise e
2023-06-23 07:32:35,642:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 981, in commit
2023-06-23 07:32:35,642:WARNING:STDERR:CMS:self.session.commit()
2023-06-23 07:32:35,642:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1903, in commit
2023-06-23 07:32:35,642:WARNING:STDERR:CMS:trans.commit(_to_root=True)
2023-06-23 07:32:35,642:WARNING:STDERR:CMS:  File "<string>", line 2, in commit
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1218, in commit
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:self._prepare_impl()
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:  File "<string>", line 2, in _prepare_impl
2023-06-23 07:32:35,643:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:self.session.flush()
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4155, in flush
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:self._flush(objects)
2023-06-23 07:32:35,644:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4292, in _flush
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:transaction.rollback(_capture_exception=True)
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4252, in _flush
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:flush_context.execute()
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
2023-06-23 07:32:35,645:WARNING:STDERR:CMS:rec.execute(self)
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:util.preloaded.orm_persistence.save_obj(
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:for (
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:for state, dict_, mapper, connection in _connections_for_states(
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1687, in _connections_for_states
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:connection = uowtransaction.transaction.connection(base_mapper)
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "<string>", line 2, in connection
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-23 07:32:35,646:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 963, in connection
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:return self._connection_for_bind(bind, execution_options)
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1096, in _connection_for_bind
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:conn = self._parent._connection_for_bind(bind, execution_options)
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:conn = bind.connect()
2023-06-23 07:32:35,647:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3251, in connect
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:return self._connection_cls(self)
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:Connection._handle_dbapi_exception_noconnection(
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2413, in _handle_dbapi_exception_noconnection
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:return self.pool.connect()
2023-06-23 07:32:35,648:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 455, in connect
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 719, in checkout
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:rec = pool._do_get()
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:self._dec_overflow()
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:return self._create_connection()
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 681, in __init__
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:self.__connect()
2023-06-23 07:32:35,649:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 906, in __connect
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 636, in connect
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:sqlalchemy.exc
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:.
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:OperationalError
2023-06-23 07:32:35,650:WARNING:STDERR:CMS::
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:(psycopg2.OperationalError) connection to server at "192.168.1.6", port 5432 failed: No route to host
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:	Is the server running on that host and accepting TCP/IP connections?
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:
2023-06-23 07:32:35,650:WARNING:STDERR:CMS:(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:32:35,651:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:32:58,139:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-23 07:33:10,143:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-23 07:33:10,312:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-23 07:34:25,122:WARNING:STDOUT:CMS:2023-06-23 07:34:25,122 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-23 07:34:25,123:WARNING:STDOUT:CMS:2023-06-23 07:34:25,123 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-23 07:34:25,137:WARNING:STDOUT:CMS:2023-06-23 07:34:25,137 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-23 07:34:25,138:WARNING:STDOUT:CMS:2023-06-23 07:34:25,138 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-23 07:34:25,148:WARNING:STDOUT:CMS:2023-06-23 07:34:25,148 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-23 07:34:25,148:WARNING:STDOUT:CMS:2023-06-23 07:34:25,148 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-23 07:34:25,160:WARNING:STDOUT:CMS:2023-06-23 07:34:25,159 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-23 07:34:25,163:WARNING:STDOUT:CMS:2023-06-23 07:34:25,163 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-23 07:34:25,163:WARNING:STDOUT:CMS:2023-06-23 07:34:25,163 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-23 07:34:25,324:WARNING:STDOUT:CMS:2023-06-23 07:34:25,324 INFO sqlalchemy.engine.Engine COMMIT
2023-06-23 07:34:25,333:WARNING:STDOUT:CMS:2023-06-23 07:34:25,332 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-23 07:34:25,334:WARNING:STDOUT:CMS:2023-06-23 07:34:25,334 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-06-23 07:34:25,334:WARNING:STDOUT:CMS:2023-06-23 07:34:25,334 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {'name': 'Cust Cart', 'hiden': True}
2023-06-23 07:34:25,349:WARNING:STDOUT:CMS:2023-06-23 07:34:25,349 INFO sqlalchemy.engine.Engine COMMIT
2023-06-23 07:34:25,357:WARNING:STDOUT:CMS:2023-06-23 07:34:25,357 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-23 07:34:25,359:WARNING:STDOUT:CMS:2023-06-23 07:34:25,359 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-06-23 07:34:25,359:WARNING:STDOUT:CMS:FROM user_grup
2023-06-23 07:34:25,359:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-06-23 07:34:25,359:WARNING:STDOUT:CMS:2023-06-23 07:34:25,359 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {'pk_1': 1}
2023-06-23 07:34:25,374:WARNING:STDOUT:CMS:2023-06-23 07:34:25,374 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-06-23 07:34:25,374:WARNING:STDOUT:CMS:2023-06-23 07:34:25,374 INFO sqlalchemy.engine.Engine [generated in 0.00028s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-06-23 07:34:25,529:WARNING:STDOUT:CMS:2023-06-23 07:34:25,529 INFO sqlalchemy.engine.Engine COMMIT
2023-06-23 07:34:25,537:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:34:25,537:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-23 07:34:25,538:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-30 20:57:32,670:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-30 20:57:44,683:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-06-30 20:57:45,023:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-06-30 20:57:57,926:WARNING:STDOUT:CMS:2023-06-30 20:57:57,926 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-06-30 20:57:57,927:WARNING:STDOUT:CMS:2023-06-30 20:57:57,927 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-30 20:57:58,049:WARNING:STDOUT:CMS:2023-06-30 20:57:58,049 INFO sqlalchemy.engine.Engine select current_schema()
2023-06-30 20:57:58,050:WARNING:STDOUT:CMS:2023-06-30 20:57:58,050 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-30 20:57:58,246:WARNING:STDOUT:CMS:2023-06-30 20:57:58,246 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-06-30 20:57:58,246:WARNING:STDOUT:CMS:2023-06-30 20:57:58,246 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-06-30 20:57:58,257:WARNING:STDOUT:CMS:2023-06-30 20:57:58,257 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-30 20:57:58,260:WARNING:STDOUT:CMS:2023-06-30 20:57:58,260 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-06-30 20:57:58,261:WARNING:STDOUT:CMS:2023-06-30 20:57:58,261 INFO sqlalchemy.engine.Engine [generated in 0.00044s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-06-30 20:57:58,462:WARNING:STDOUT:CMS:2023-06-30 20:57:58,462 INFO sqlalchemy.engine.Engine COMMIT
2023-06-30 20:57:58,656:WARNING:STDOUT:CMS:2023-06-30 20:57:58,656 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-30 20:57:58,657:WARNING:STDOUT:CMS:2023-06-30 20:57:58,657 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-06-30 20:57:58,657:WARNING:STDOUT:CMS:2023-06-30 20:57:58,657 INFO sqlalchemy.engine.Engine [generated in 0.00016s] {'name': 'Cust Cart', 'hiden': True}
2023-06-30 20:57:58,860:WARNING:STDOUT:CMS:2023-06-30 20:57:58,860 INFO sqlalchemy.engine.Engine COMMIT
2023-06-30 20:57:58,868:WARNING:STDOUT:CMS:2023-06-30 20:57:58,868 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-30 20:57:58,871:WARNING:STDOUT:CMS:2023-06-30 20:57:58,871 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-06-30 20:57:58,871:WARNING:STDOUT:CMS:FROM user_grup
2023-06-30 20:57:58,871:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-06-30 20:57:58,871:WARNING:STDOUT:CMS:2023-06-30 20:57:58,871 INFO sqlalchemy.engine.Engine [generated in 0.00053s] {'pk_1': 1}
2023-06-30 20:57:58,887:WARNING:STDOUT:CMS:2023-06-30 20:57:58,887 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-06-30 20:57:58,887:WARNING:STDOUT:CMS:2023-06-30 20:57:58,887 INFO sqlalchemy.engine.Engine [generated in 0.00048s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-06-30 20:57:59,216:WARNING:STDOUT:CMS:2023-06-30 20:57:59,216 INFO sqlalchemy.engine.Engine COMMIT
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-06-30 20:57:59,227:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-17 12:52:44,741:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-07-17 12:52:56,762:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-07-17 12:52:56,965:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-07-17 12:53:03,757:WARNING:STDOUT:CMS:2023-07-17 12:53:03,757 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-07-17 12:53:03,757:WARNING:STDOUT:CMS:2023-07-17 12:53:03,757 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-17 12:53:03,771:WARNING:STDOUT:CMS:2023-07-17 12:53:03,770 INFO sqlalchemy.engine.Engine select current_schema()
2023-07-17 12:53:03,771:WARNING:STDOUT:CMS:2023-07-17 12:53:03,771 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-17 12:53:03,825:WARNING:STDOUT:CMS:2023-07-17 12:53:03,825 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-07-17 12:53:03,825:WARNING:STDOUT:CMS:2023-07-17 12:53:03,825 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-17 12:53:03,837:WARNING:STDOUT:CMS:2023-07-17 12:53:03,837 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-17 12:53:03,840:WARNING:STDOUT:CMS:2023-07-17 12:53:03,840 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-07-17 12:53:03,841:WARNING:STDOUT:CMS:2023-07-17 12:53:03,841 INFO sqlalchemy.engine.Engine [generated in 0.00047s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-07-17 12:53:03,858:WARNING:STDOUT:CMS:2023-07-17 12:53:03,858 INFO sqlalchemy.engine.Engine COMMIT
2023-07-17 12:53:04,031:WARNING:STDOUT:CMS:2023-07-17 12:53:04,031 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-17 12:53:04,032:WARNING:STDOUT:CMS:2023-07-17 12:53:04,032 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-07-17 12:53:04,033:WARNING:STDOUT:CMS:2023-07-17 12:53:04,033 INFO sqlalchemy.engine.Engine [generated in 0.00046s] {'name': 'Cust Cart', 'hiden': True}
2023-07-17 12:53:04,046:WARNING:STDOUT:CMS:2023-07-17 12:53:04,046 INFO sqlalchemy.engine.Engine COMMIT
2023-07-17 12:53:04,056:WARNING:STDOUT:CMS:2023-07-17 12:53:04,056 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-17 12:53:04,058:WARNING:STDOUT:CMS:2023-07-17 12:53:04,058 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-07-17 12:53:04,058:WARNING:STDOUT:CMS:FROM user_grup
2023-07-17 12:53:04,059:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-07-17 12:53:04,059:WARNING:STDOUT:CMS:2023-07-17 12:53:04,059 INFO sqlalchemy.engine.Engine [generated in 0.00038s] {'pk_1': 1}
2023-07-17 12:53:04,240:WARNING:STDOUT:CMS:2023-07-17 12:53:04,239 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-07-17 12:53:04,240:WARNING:STDOUT:CMS:2023-07-17 12:53:04,240 INFO sqlalchemy.engine.Engine [generated in 0.00058s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-07-17 12:53:04,553:WARNING:STDOUT:CMS:2023-07-17 12:53:04,553 INFO sqlalchemy.engine.Engine COMMIT
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-17 12:53:04,561:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-19 23:38:14,350:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-07-19 23:38:26,365:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-07-19 23:38:26,546:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-07-19 23:38:38,557:WARNING:STDOUT:CMS:2023-07-19 23:38:38,557 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-07-19 23:38:38,558:WARNING:STDOUT:CMS:2023-07-19 23:38:38,558 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-19 23:38:38,569:WARNING:STDOUT:CMS:2023-07-19 23:38:38,569 INFO sqlalchemy.engine.Engine select current_schema()
2023-07-19 23:38:38,570:WARNING:STDOUT:CMS:2023-07-19 23:38:38,569 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-19 23:38:38,580:WARNING:STDOUT:CMS:2023-07-19 23:38:38,579 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-07-19 23:38:38,580:WARNING:STDOUT:CMS:2023-07-19 23:38:38,580 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-07-19 23:38:38,594:WARNING:STDOUT:CMS:2023-07-19 23:38:38,594 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-19 23:38:38,597:WARNING:STDOUT:CMS:2023-07-19 23:38:38,597 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-07-19 23:38:38,598:WARNING:STDOUT:CMS:2023-07-19 23:38:38,597 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-07-19 23:38:38,615:WARNING:STDOUT:CMS:2023-07-19 23:38:38,615 INFO sqlalchemy.engine.Engine COMMIT
2023-07-19 23:38:38,849:WARNING:STDOUT:CMS:2023-07-19 23:38:38,849 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-19 23:38:38,850:WARNING:STDOUT:CMS:2023-07-19 23:38:38,850 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-07-19 23:38:38,851:WARNING:STDOUT:CMS:2023-07-19 23:38:38,851 INFO sqlalchemy.engine.Engine [generated in 0.00033s] {'name': 'Cust Cart', 'hiden': True}
2023-07-19 23:38:38,865:WARNING:STDOUT:CMS:2023-07-19 23:38:38,865 INFO sqlalchemy.engine.Engine COMMIT
2023-07-19 23:38:38,876:WARNING:STDOUT:CMS:2023-07-19 23:38:38,876 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-19 23:38:38,880:WARNING:STDOUT:CMS:2023-07-19 23:38:38,880 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-07-19 23:38:38,880:WARNING:STDOUT:CMS:FROM user_grup
2023-07-19 23:38:38,880:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-07-19 23:38:38,880:WARNING:STDOUT:CMS:2023-07-19 23:38:38,880 INFO sqlalchemy.engine.Engine [generated in 0.00057s] {'pk_1': 1}
2023-07-19 23:38:38,896:WARNING:STDOUT:CMS:2023-07-19 23:38:38,896 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-07-19 23:38:38,896:WARNING:STDOUT:CMS:2023-07-19 23:38:38,896 INFO sqlalchemy.engine.Engine [generated in 0.00053s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-07-19 23:38:38,913:WARNING:STDOUT:CMS:2023-07-19 23:38:38,913 INFO sqlalchemy.engine.Engine COMMIT
2023-07-19 23:38:38,919:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-19 23:38:38,920:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-19 23:38:38,921:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-07-19 23:38:38,921:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:00:28,458:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-08-16 21:00:40,470:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-08-16 21:00:40,665:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-08-16 21:01:16,410:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-08-16 21:01:16,410:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2023-08-16 21:01:16,411:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2023-08-16 21:01:16,411:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:return self.pool.connect()
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 455, in connect
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 719, in checkout
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:rec = pool._do_get()
2023-08-16 21:01:16,412:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:self._dec_overflow()
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:return self._create_connection()
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2023-08-16 21:01:16,413:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 681, in __init__
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:self.__connect()
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 906, in __connect
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 636, in connect
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2023-08-16 21:01:16,414:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:psycopg2
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:.
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:OperationalError
2023-08-16 21:01:16,415:WARNING:STDERR:CMS::
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:could not translate host name "192.168..1.11" to address: Name or service not known
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:The above exception was the direct cause of the following exception:
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:Traceback (most recent call last):
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 201, in <module>
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:db_init_new()
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 173, in db_init_new
2023-08-16 21:01:16,415:WARNING:STDERR:CMS:DB.commit()
2023-08-16 21:01:16,416:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 990, in commit
2023-08-16 21:01:16,416:WARNING:STDERR:CMS:raise e
2023-08-16 21:01:16,416:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 985, in commit
2023-08-16 21:01:16,416:WARNING:STDERR:CMS:self.session.commit()
2023-08-16 21:01:16,416:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1903, in commit
2023-08-16 21:01:16,417:WARNING:STDERR:CMS:trans.commit(_to_root=True)
2023-08-16 21:01:16,417:WARNING:STDERR:CMS:  File "<string>", line 2, in commit
2023-08-16 21:01:16,417:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-08-16 21:01:16,417:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-08-16 21:01:16,417:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1218, in commit
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:self._prepare_impl()
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:  File "<string>", line 2, in _prepare_impl
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:self.session.flush()
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4155, in flush
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:self._flush(objects)
2023-08-16 21:01:16,418:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4292, in _flush
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:transaction.rollback(_capture_exception=True)
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4252, in _flush
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:flush_context.execute()
2023-08-16 21:01:16,419:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:rec.execute(self)
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:util.preloaded.orm_persistence.save_obj(
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:for (
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:for state, dict_, mapper, connection in _connections_for_states(
2023-08-16 21:01:16,420:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1687, in _connections_for_states
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:connection = uowtransaction.transaction.connection(base_mapper)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "<string>", line 2, in connection
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 963, in connection
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:return self._connection_for_bind(bind, execution_options)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1096, in _connection_for_bind
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:conn = self._parent._connection_for_bind(bind, execution_options)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2023-08-16 21:01:16,421:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:conn = bind.connect()
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3251, in connect
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:return self._connection_cls(self)
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:Connection._handle_dbapi_exception_noconnection(
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2413, in _handle_dbapi_exception_noconnection
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2023-08-16 21:01:16,422:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:return self.pool.connect()
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 455, in connect
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 719, in checkout
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:rec = pool._do_get()
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:self._dec_overflow()
2023-08-16 21:01:16,423:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:return self._create_connection()
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 681, in __init__
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:self.__connect()
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 906, in __connect
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2023-08-16 21:01:16,424:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 636, in connect
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:sqlalchemy.exc
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:.
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:OperationalError
2023-08-16 21:01:16,425:WARNING:STDERR:CMS::
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:(psycopg2.OperationalError) could not translate host name "192.168..1.11" to address: Name or service not known
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:
2023-08-16 21:01:16,425:WARNING:STDERR:CMS:(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:01:16,426:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:01:41,696:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-08-16 21:01:53,711:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2023-08-16 21:01:53,834:WARNING:STDOUT:CMS:SET IP ADRESS:
2023-08-16 21:02:16,742:WARNING:STDOUT:CMS:2023-08-16 21:02:16,742 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-08-16 21:02:16,743:WARNING:STDOUT:CMS:2023-08-16 21:02:16,743 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-08-16 21:02:17,357:WARNING:STDOUT:CMS:2023-08-16 21:02:17,357 INFO sqlalchemy.engine.Engine select current_schema()
2023-08-16 21:02:17,357:WARNING:STDOUT:CMS:2023-08-16 21:02:17,357 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-08-16 21:02:17,518:WARNING:STDOUT:CMS:2023-08-16 21:02:17,518 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-08-16 21:02:17,519:WARNING:STDOUT:CMS:2023-08-16 21:02:17,519 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-08-16 21:02:17,795:WARNING:STDOUT:CMS:2023-08-16 21:02:17,795 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-08-16 21:02:17,799:WARNING:STDOUT:CMS:2023-08-16 21:02:17,799 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2023-08-16 21:02:17,799:WARNING:STDOUT:CMS:2023-08-16 21:02:17,799 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (107 characters truncated) ... , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2023-08-16 21:02:18,167:WARNING:STDOUT:CMS:2023-08-16 21:02:18,167 INFO sqlalchemy.engine.Engine COMMIT
2023-08-16 21:02:18,410:WARNING:STDOUT:CMS:2023-08-16 21:02:18,410 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-08-16 21:02:18,411:WARNING:STDOUT:CMS:2023-08-16 21:02:18,411 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2023-08-16 21:02:18,411:WARNING:STDOUT:CMS:2023-08-16 21:02:18,411 INFO sqlalchemy.engine.Engine [generated in 0.00018s] {'name': 'Cust Cart', 'hiden': True}
2023-08-16 21:02:18,787:WARNING:STDOUT:CMS:2023-08-16 21:02:18,787 INFO sqlalchemy.engine.Engine COMMIT
2023-08-16 21:02:18,799:WARNING:STDOUT:CMS:2023-08-16 21:02:18,799 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-08-16 21:02:18,802:WARNING:STDOUT:CMS:2023-08-16 21:02:18,802 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2023-08-16 21:02:18,802:WARNING:STDOUT:CMS:FROM user_grup
2023-08-16 21:02:18,802:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2023-08-16 21:02:18,803:WARNING:STDOUT:CMS:2023-08-16 21:02:18,802 INFO sqlalchemy.engine.Engine [generated in 0.00049s] {'pk_1': 1}
2023-08-16 21:02:18,820:WARNING:STDOUT:CMS:2023-08-16 21:02:18,820 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2023-08-16 21:02:18,820:WARNING:STDOUT:CMS:2023-08-16 21:02:18,820 INFO sqlalchemy.engine.Engine [generated in 0.00052s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2023-08-16 21:02:19,029:WARNING:STDOUT:CMS:2023-08-16 21:02:19,028 INFO sqlalchemy.engine.Engine COMMIT
2023-08-16 21:02:19,398:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:02:19,398:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:02:19,398:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2023-08-16 21:02:19,399:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 07:56:07,279:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-03 07:56:19,294:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-03 07:56:19,427:WARNING:STDOUT:CMS:SET IP ADRESS:
2024-11-03 07:56:56,451:WARNING:STDERR:CMS:Traceback (most recent call last):
2024-11-03 07:56:56,452:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2024-11-03 07:56:56,457:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2024-11-03 07:56:56,457:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
2024-11-03 07:56:56,458:WARNING:STDERR:CMS:return self.pool.connect()
2024-11-03 07:56:56,458:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:rec = pool._do_get()
2024-11-03 07:56:56,459:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:self._dec_overflow()
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:return self._create_connection()
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:self.__connect()
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2024-11-03 07:56:56,460:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 640, in connect
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2024-11-03 07:56:56,461:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:psycopg2
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:.
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:OperationalError
2024-11-03 07:56:56,462:WARNING:STDERR:CMS::
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:connection to server at "192.168.2.11", port 5432 failed: timeout expired
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:The above exception was the direct cause of the following exception:
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:Traceback (most recent call last):
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 204, in <module>
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:db_init_new()
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 176, in db_init_new
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:DB.commit()
2024-11-03 07:56:56,462:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 1011, in commit
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:raise e
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 1006, in commit
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:self.session.commit()
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1903, in commit
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:trans.commit(_to_root=True)
2024-11-03 07:56:56,463:WARNING:STDERR:CMS:  File "<string>", line 2, in commit
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1218, in commit
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:self._prepare_impl()
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:  File "<string>", line 2, in _prepare_impl
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-03 07:56:56,464:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
2024-11-03 07:56:56,465:WARNING:STDERR:CMS:self.session.flush()
2024-11-03 07:56:56,465:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4140, in flush
2024-11-03 07:56:56,465:WARNING:STDERR:CMS:self._flush(objects)
2024-11-03 07:56:56,465:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4277, in _flush
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:transaction.rollback(_capture_exception=True)
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4237, in _flush
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:flush_context.execute()
2024-11-03 07:56:56,466:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:rec.execute(self)
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:util.preloaded.orm_persistence.save_obj(
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:for (
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:for state, dict_, mapper, connection in _connections_for_states(
2024-11-03 07:56:56,467:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1695, in _connections_for_states
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:connection = uowtransaction.transaction.connection(base_mapper)
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "<string>", line 2, in connection
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 963, in connection
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:return self._connection_for_bind(bind, execution_options)
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1096, in _connection_for_bind
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:conn = self._parent._connection_for_bind(bind, execution_options)
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-03 07:56:56,468:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:conn = bind.connect()
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3245, in connect
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:return self._connection_cls(self)
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:Connection._handle_dbapi_exception_noconnection(
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2410, in _handle_dbapi_exception_noconnection
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2024-11-03 07:56:56,469:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:return self.pool.connect()
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:rec = pool._do_get()
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2024-11-03 07:56:56,470:WARNING:STDERR:CMS:self._dec_overflow()
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:return self._create_connection()
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:self.__connect()
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-03 07:56:56,471:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 640, in connect
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:sqlalchemy.exc
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:.
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:OperationalError
2024-11-03 07:56:56,472:WARNING:STDERR:CMS::
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:(psycopg2.OperationalError) connection to server at "192.168.2.11", port 5432 failed: timeout expired
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 07:56:56,472:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 07:56:56,473:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 08:05:19,468:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-03 08:05:31,482:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-03 08:05:31,660:WARNING:STDOUT:CMS:SET IP ADRESS:
2024-11-03 08:05:39,437:WARNING:STDOUT:CMS:2024-11-03 08:05:39,437 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2024-11-03 08:05:39,437:WARNING:STDOUT:CMS:2024-11-03 08:05:39,437 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-03 08:05:39,453:WARNING:STDOUT:CMS:2024-11-03 08:05:39,453 INFO sqlalchemy.engine.Engine select current_schema()
2024-11-03 08:05:39,453:WARNING:STDOUT:CMS:2024-11-03 08:05:39,453 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-03 08:05:39,648:WARNING:STDOUT:CMS:2024-11-03 08:05:39,648 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2024-11-03 08:05:39,648:WARNING:STDOUT:CMS:2024-11-03 08:05:39,648 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-03 08:05:39,663:WARNING:STDOUT:CMS:2024-11-03 08:05:39,663 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-03 08:05:39,667:WARNING:STDOUT:CMS:2024-11-03 08:05:39,667 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2024-11-03 08:05:39,667:WARNING:STDOUT:CMS:2024-11-03 08:05:39,667 INFO sqlalchemy.engine.Engine [generated in 0.00048s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (117 characters truncated) ... , 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1, 2], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2024-11-03 08:05:39,772:WARNING:STDOUT:CMS:2024-11-03 08:05:39,772 INFO sqlalchemy.engine.Engine COMMIT
2024-11-03 08:05:39,847:WARNING:STDOUT:CMS:2024-11-03 08:05:39,847 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-03 08:05:39,848:WARNING:STDOUT:CMS:2024-11-03 08:05:39,848 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2024-11-03 08:05:39,848:WARNING:STDOUT:CMS:2024-11-03 08:05:39,848 INFO sqlalchemy.engine.Engine [generated in 0.00030s] {'name': 'Cust Cart', 'hiden': True}
2024-11-03 08:05:40,053:WARNING:STDOUT:CMS:2024-11-03 08:05:40,053 INFO sqlalchemy.engine.Engine COMMIT
2024-11-03 08:05:40,257:WARNING:STDOUT:CMS:2024-11-03 08:05:40,256 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-03 08:05:40,260:WARNING:STDOUT:CMS:2024-11-03 08:05:40,260 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2024-11-03 08:05:40,260:WARNING:STDOUT:CMS:FROM user_grup
2024-11-03 08:05:40,260:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2024-11-03 08:05:40,261:WARNING:STDOUT:CMS:2024-11-03 08:05:40,261 INFO sqlalchemy.engine.Engine [generated in 0.00070s] {'pk_1': 1}
2024-11-03 08:05:40,285:WARNING:STDOUT:CMS:2024-11-03 08:05:40,285 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2024-11-03 08:05:40,285:WARNING:STDOUT:CMS:2024-11-03 08:05:40,285 INFO sqlalchemy.engine.Engine [generated in 0.00055s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2024-11-03 08:05:40,461:WARNING:STDOUT:CMS:2024-11-03 08:05:40,461 INFO sqlalchemy.engine.Engine COMMIT
2024-11-03 08:05:40,468:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-03 08:05:40,469:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:52:40,308:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-07 11:52:52,326:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-07 11:52:52,507:WARNING:STDOUT:CMS:SET IP ADRESS:
2024-11-07 11:54:37,612:WARNING:STDERR:CMS:Traceback (most recent call last):
2024-11-07 11:54:37,613:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2024-11-07 11:54:37,614:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2024-11-07 11:54:37,614:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
2024-11-07 11:54:37,615:WARNING:STDERR:CMS:return self.pool.connect()
2024-11-07 11:54:37,615:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
2024-11-07 11:54:37,615:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2024-11-07 11:54:37,615:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:rec = pool._do_get()
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:self._dec_overflow()
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:return self._create_connection()
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
2024-11-07 11:54:37,616:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:self.__connect()
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 640, in connect
2024-11-07 11:54:37,617:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:psycopg2
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:.
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:OperationalError
2024-11-07 11:54:37,618:WARNING:STDERR:CMS::
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:connection to server at "192.168.2.11", port 5432 failed: timeout expired
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:
2024-11-07 11:54:37,618:WARNING:STDERR:CMS:The above exception was the direct cause of the following exception:
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:Traceback (most recent call last):
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 204, in <module>
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:db_init_new()
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/gui_lib/right.py", line 176, in db_init_new
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:DB.commit()
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 1011, in commit
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:raise e
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/models.py", line 1006, in commit
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:self.session.commit()
2024-11-07 11:54:37,619:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1903, in commit
2024-11-07 11:54:37,620:WARNING:STDERR:CMS:trans.commit(_to_root=True)
2024-11-07 11:54:37,620:WARNING:STDERR:CMS:  File "<string>", line 2, in commit
2024-11-07 11:54:37,620:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-07 11:54:37,620:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1218, in commit
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:self._prepare_impl()
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:  File "<string>", line 2, in _prepare_impl
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:self.session.flush()
2024-11-07 11:54:37,621:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4140, in flush
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:self._flush(objects)
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4277, in _flush
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:transaction.rollback(_capture_exception=True)
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-07 11:54:37,622:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4237, in _flush
2024-11-07 11:54:37,623:WARNING:STDERR:CMS:flush_context.execute()
2024-11-07 11:54:37,623:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
2024-11-07 11:54:37,623:WARNING:STDERR:CMS:rec.execute(self)
2024-11-07 11:54:37,623:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
2024-11-07 11:54:37,623:WARNING:STDERR:CMS:util.preloaded.orm_persistence.save_obj(
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:for (
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:for state, dict_, mapper, connection in _connections_for_states(
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1695, in _connections_for_states
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:connection = uowtransaction.transaction.connection(base_mapper)
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "<string>", line 2, in connection
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-07 11:54:37,624:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 963, in connection
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:return self._connection_for_bind(bind, execution_options)
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1096, in _connection_for_bind
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:conn = self._parent._connection_for_bind(bind, execution_options)
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "<string>", line 2, in _connection_for_bind
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:ret_value = fn(self, *arg, **kw)
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:conn = bind.connect()
2024-11-07 11:54:37,625:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3245, in connect
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:return self._connection_cls(self)
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:Connection._handle_dbapi_exception_noconnection(
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2410, in _handle_dbapi_exception_noconnection
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:self._dbapi_connection = engine.raw_connection()
2024-11-07 11:54:37,626:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:return self.pool.connect()
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:return _ConnectionFairy._checkout(self)
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:fairy = _ConnectionRecord.checkout(pool)
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:rec = pool._do_get()
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:self._dec_overflow()
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2024-11-07 11:54:37,627:WARNING:STDERR:CMS:return self._create_connection()
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:return _ConnectionRecord(self)
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:self.__connect()
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:pool.logger.debug("Error on connect(): %s", e)
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:raise exc_value.with_traceback(exc_tb)
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:self.dbapi_connection = connection = pool._invoke_creator(self)
2024-11-07 11:54:37,628:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 640, in connect
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:return dialect.connect(*cargs, **cparams)
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 580, in connect
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:return self.loaded_dbapi.connect(*cargs, **cparams)
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:sqlalchemy.exc
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:.
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:OperationalError
2024-11-07 11:54:37,629:WARNING:STDERR:CMS::
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:(psycopg2.OperationalError) connection to server at "192.168.2.11", port 5432 failed: timeout expired
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:54:37,629:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:54:37,630:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:54:37,630:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:54:37,630:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:54:37,630:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:54:51,586:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-07 11:55:03,600:ERROR:STDERR:CMS:timed out
Traceback (most recent call last):
  File "/home/dedal/Colibri/ColibriCMS/2_1/libs/sock/udp_socket/client.py", line 115, in getfrom
    data = self.s.recv(self.udp_buffer)
socket.timeout: timed out
2024-11-07 11:55:03,740:WARNING:STDOUT:CMS:SET IP ADRESS:
2024-11-07 11:55:14,367:WARNING:STDOUT:CMS:2024-11-07 11:55:14,367 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2024-11-07 11:55:14,367:WARNING:STDOUT:CMS:2024-11-07 11:55:14,367 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-07 11:55:14,514:WARNING:STDOUT:CMS:2024-11-07 11:55:14,514 INFO sqlalchemy.engine.Engine select current_schema()
2024-11-07 11:55:14,514:WARNING:STDOUT:CMS:2024-11-07 11:55:14,514 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-07 11:55:14,530:WARNING:STDOUT:CMS:2024-11-07 11:55:14,530 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2024-11-07 11:55:14,530:WARNING:STDOUT:CMS:2024-11-07 11:55:14,530 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-11-07 11:55:14,546:WARNING:STDOUT:CMS:2024-11-07 11:55:14,545 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-07 11:55:14,549:WARNING:STDOUT:CMS:2024-11-07 11:55:14,549 INFO sqlalchemy.engine.Engine INSERT INTO user_grup (name, "right") VALUES (%(name)s, %(right)s) RETURNING user_grup.id, user_grup.default_use, user_grup.auto_mail, user_grup.rko_auto_mail, user_grup.bill_disable, user_grup.get_all_bill, user_grup.boss_mail, user_grup.service_mail, user_grup.subject
2024-11-07 11:55:14,549:WARNING:STDOUT:CMS:2024-11-07 11:55:14,549 INFO sqlalchemy.engine.Engine [generated in 0.00045s] {'name': 'OWNER', 'right': '{"main": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "cust": [1, 2, 3, 4, 5, 6, 7, 8, 9, ... (117 characters truncated) ... , 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "user": [1, 2, 3, 4], "mashin": [1, 2, 3, 4, 5, 6, 7], "diff": [1, 2], "report": [1, 2, 3, 4, 5, 6, 7, 8]}'}
2024-11-07 11:55:14,978:WARNING:STDOUT:CMS:2024-11-07 11:55:14,978 INFO sqlalchemy.engine.Engine COMMIT
2024-11-07 11:55:15,180:WARNING:STDOUT:CMS:2024-11-07 11:55:15,180 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-07 11:55:15,181:WARNING:STDOUT:CMS:2024-11-07 11:55:15,181 INFO sqlalchemy.engine.Engine INSERT INTO prihod_type (name, hiden) VALUES (%(name)s, %(hiden)s) RETURNING prihod_type.id
2024-11-07 11:55:15,182:WARNING:STDOUT:CMS:2024-11-07 11:55:15,182 INFO sqlalchemy.engine.Engine [generated in 0.00039s] {'name': 'Cust Cart', 'hiden': True}
2024-11-07 11:55:15,383:WARNING:STDOUT:CMS:2024-11-07 11:55:15,383 INFO sqlalchemy.engine.Engine COMMIT
2024-11-07 11:55:15,394:WARNING:STDOUT:CMS:2024-11-07 11:55:15,394 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-07 11:55:15,397:WARNING:STDOUT:CMS:2024-11-07 11:55:15,397 INFO sqlalchemy.engine.Engine SELECT user_grup.id AS user_grup_id, user_grup.name AS user_grup_name, user_grup."right" AS user_grup_right, user_grup.default_use AS user_grup_default_use, user_grup.auto_mail AS user_grup_auto_mail, user_grup.rko_auto_mail AS user_grup_rko_auto_mail, user_grup.bill_disable AS user_grup_bill_disable, user_grup.get_all_bill AS user_grup_get_all_bill, user_grup.boss_mail AS user_grup_boss_mail, user_grup.service_mail AS user_grup_service_mail, user_grup.subject AS user_grup_subject
2024-11-07 11:55:15,397:WARNING:STDOUT:CMS:FROM user_grup
2024-11-07 11:55:15,397:WARNING:STDOUT:CMS:WHERE user_grup.id = %(pk_1)s
2024-11-07 11:55:15,398:WARNING:STDOUT:CMS:2024-11-07 11:55:15,398 INFO sqlalchemy.engine.Engine [generated in 0.00054s] {'pk_1': 1}
2024-11-07 11:55:15,417:WARNING:STDOUT:CMS:2024-11-07 11:55:15,417 INFO sqlalchemy.engine.Engine INSERT INTO users (name, passwd, cart, cart_block_9, grup_id, enable, flor_id, login) VALUES (%(name)s, %(passwd)s, %(cart)s, %(cart_block_9)s, %(grup_id)s, %(enable)s, %(flor_id)s, %(login)s) RETURNING users.id, users.kasa, users.lipsi
2024-11-07 11:55:15,417:WARNING:STDOUT:CMS:2024-11-07 11:55:15,417 INFO sqlalchemy.engine.Engine [generated in 0.00054s] {'name': 'root', 'passwd': '123456', 'cart': None, 'cart_block_9': None, 'grup_id': 1, 'enable': True, 'flor_id': None, 'login': False}
2024-11-07 11:55:15,430:WARNING:STDOUT:CMS:2024-11-07 11:55:15,430 INFO sqlalchemy.engine.Engine COMMIT
2024-11-07 11:55:15,589:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:55:15,589:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:55:15,589:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:55:15,589:WARNING:STDERR:CMS:[INFO/MainProcess] process shutting down
2024-11-07 11:55:15,589:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
2024-11-07 11:55:15,590:WARNING:STDERR:CMS:[DEBUG/MainProcess] running the remaining "atexit" finalizers
